<a href="https://colab.research.google.com/github/SankirthGunnam/FastAI/blob/main/numpy_tutor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

### 1D Array (Vector)

In [13]:
mylist = [1,2,3,4,5]
arr = np.array(mylist)
arr

array([1, 2, 3, 4, 5])

In [14]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(5,)
1
int64


In [20]:
# 2D array
arr2 = [[1,2,3], [4,5,6]]
arr2 = np.array(arr2)
print(arr2, arr2.shape, arr2.dtype, arr2.ndim, sep=', ')

[[1 2 3]
 [4 5 6]], (2, 3), int64, 2


In [24]:
zrs = np.zeros((2,3))
zrs

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
a3 = np.full((2,3), 1)
a3

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
# Fill size can be scaler or vector, if vector should match the row size
# For ex: np.full((2,5), <should be scaler or vector of length 5>)
a3 = np.full((2,5), 1)
print(a3)
a4 = np.full((2,5), [1,2,3,4,5])
print(a4)

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [50]:
# Below will throw an error
# a5 = np.full((2,5), [1,2])

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipython-input-48-1049343758.py in <cell line: 0>()
      1 # Below will throw an error
----> 2 a5 = np.full((2,5), [1,2])

/usr/local/lib/python3.11/dist-packages/numpy/_core/numeric.py in full(shape, fill_value, dtype, order, device, like)
    360         dtype = fill_value.dtype
    361     a = empty(shape, dtype, order, device=device)
--> 362     multiarray.copyto(a, fill_value, casting='unsafe')
    363     return a
    364

ValueError: could not broadcast input array from shape (2,) into shape (2,5)

In [59]:
ar = np.arange(10)
print(ar)
ar2 = np.arange(5, 10)
print(ar2)
ar3 = np.arange(1, 10, 3)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[1 4 7]
