<a href="https://colab.research.google.com/github/SankirthGunnam/FastAI/blob/main/numpy_tutor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

### 1D Array (Vector)

In [13]:
mylist = [1,2,3,4,5]
arr = np.array(mylist)
arr

array([1, 2, 3, 4, 5])

In [14]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(5,)
1
int64


In [20]:
# 2D array
arr2 = [[1,2,3], [4,5,6]]
arr2 = np.array(arr2)
print(arr2, arr2.shape, arr2.dtype, arr2.ndim, sep=', ')

[[1 2 3]
 [4 5 6]], (2, 3), int64, 2


In [24]:
zrs = np.zeros((2,3))
zrs

array([[0., 0., 0.],
       [0., 0., 0.]])